<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DentZone_Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentZone.Application\DentZone.Application.csproj" />
    <ProjectReference Include="..\DentZone.Infrastructure\DentZone.Infrastructure.csproj" />
    <ProjectReference Include="..\DentZone.Persistence\DentZone.Persistence.csproj" />
  </ItemGroup>

</Project>
